### ISSUE TITLE
Release of test set

### ISSUE THREAD

**Issue by DSKSD** [McGill-NLP/topiocqa#6]
Hi,
Again, thank you for the great work!

Do you have any plan to release test set?
Otherwise, how can I evaluate my model on the test set?

Thanks,
Best,

**Comment by vaibhavad** [comment]
Hi,

Thank you for your interest in our work. We currently do not plan to release the test set. We are constructing a shared task/leaderboard for the dataset. The test set will be used as a hidden evaluation set in that.

I will share more details of this shared task/leaderboard once it is finalized.
