### ISSUE TITLE
size of Wikipedia corpus

### ISSUE THREAD

**Issue by seahou3e** [McGill-NLP/topiocqa#7]
I have not downloaded the Wikipedia corpus (by running `python download_data.py --resource data.wikipedia_split.full_wiki`) since I expect it to be very large. I need to allocate disk space, may I know what the size (in GB, TB?) will be? Thanks.

**Comment by vaibhavad** [comment]
Hi,

Thank you for your interest in our work. The `data.wikipedia_split.full_wiki` is approximately 31.4 GB. You can check [here](https://zenodo.org/record/6173228#.YiY0_5PMK3I).

However, this is the raw Wikipedia dump that has a lot of extra information which is not used (links, NER, etc). The pruned and segmented Wikipedia file used by the models can be downloaded by using `data.wikipedia_split.full_wiki_segments` resource key. This is approximately [12-13 GB](https://zenodo.org/record/6149599#.YiY13ZPMK3I)

**Comment by seahou3e** [comment]
> Hi,
> 
> Thank you for your interest in our work. The `data.wikipedia_split.full_wiki` is approximately 31.4 GB. You can check [here](https://zenodo.org/record/6173228#.YiY0_5PMK3I).
> 
> However, this is the raw Wikipedia dump that has a lot of extra information which is not used (links, NER, etc). The pruned and segmented Wikipedia file used by the models can be downloaded by using `data.wikipedia_split.full_wiki_segments` resource key. This is approximately [12-13 GB](https://zenodo.org/record/6149599#.YiY13ZPMK3I)

Thanks!   Closing the issue.
